# Generated by Django 4.2.8 on 2024-05-20 07:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userinfo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='age',
            new_name='era',
        ),
        migrations.RenameField(
            model_name='userinfo',
            old_name='sex',
            new_name='gender',
        ),
    ]
