# Generated by Django 4.2.8 on 2024-05-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_age_userinfo_era_rename_sex_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.TextField(),
        ),
    ]
