# Generated by Django 4.2.8 on 2024-05-21 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userinfo_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='favorite_genre',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
