# Generated by Django 4.2.8 on 2024-05-21 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_userinfo_favorite_genre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userinfo',
            name='user_id',
        ),
        migrations.AddField(
            model_name='userinfo',
            name='isSpecial',
            field=models.BooleanField(default=False),
        ),
    ]
