# Generated by Django 4.2.8 on 2024-05-21 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_userinfo_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinfo',
            name='favorite_genre',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
