# Generated by Django 4.2.8 on 2024-05-20 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_backdrop_path_alter_movie_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieGenreInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_id1', models.IntegerField()),
                ('genre_id2', models.IntegerField(null=True)),
                ('genre_id3', models.IntegerField(null=True)),
                ('genre_id4', models.IntegerField(null=True)),
                ('genre_id5', models.IntegerField(null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
            ],
        ),
    ]
