# Generated by Django 4.2.8 on 2024-05-20 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_moviegenreinfo_movie_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre_ids',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
