# Generated by Django 4.2.8 on 2024-05-21 02:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_movie_genre_ids'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MovieGenreInfo',
        ),
    ]
